services:
  ipwho-web:
    image: ghcr.io/machka-pasla/ipwho:web
    container_name: ipwho-web
    hostname: ipwho-web
    networks:
      - ipwho-network
    restart: unless-stopped
    env_file:
      - .env
    command: python -m app.web

  ipwho-bot:
    image: ghcr.io/machka-pasla/ipwho:bot
    container_name: ipwho-bot
    hostname: ipwho-bot
    restart: unless-stopped
    networks:
      - ipwho-network
    env_file:
      - .env
    command: python -m app.bot

networks:
  ipwho-network:
    external: true
